[package]
name = "tlang_semantics"
version = "0.1.0"
edition.workspace = true

[dependencies]
tlang_ast = { path = "../tlang_ast" }

[dev-dependencies]
tlang_parser = { path = "../tlang_parser" }
indoc = { workspace = true }
pretty_assertions = { workspace = true }
