[package]
name = "tlang_symbols"
version = "0.1.0"
edition.workspace = true

[dependencies]
log.workspace = true
tlang_span = { path = "../tlang_span" }

[dependencies.serde]
workspace = true
optional = true

[features]
serde = ["dep:serde", "tlang_span/serde"]