# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      testing:
        patterns:
          - ctor
          - indoc
          - insta
          - pretty_assertions
      wasm:
        patterns:
          - 'wasm-bindgen'
          - 'web-sys'
          - 'js-sys'
      serde:
        patterns:
          - 'serde'
          - 'serde_*'
      proc_macro:
        patterns:
          - 'syn'
          - 'quote'
  - package-ecosystem: 'npm'
    versioning-strategy: 'increase'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      linting-formatting:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'globals'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
          - 'prettier'
          - 'postcss-lit'
          - 'stylelint'
          - 'stylelint-config-standard'
      lit:
        patterns:
          - 'lit'
          - 'ts-lit-plugin'
      typescript:
        patterns:
          - 'typescript'
          - 'tslib'
          - 'ts-node'
          - '@types/node'
          - 'node-dev'
