[package]
name = "tlang_memory"
version = "0.1.0"
edition.workspace = true

[lib]
name = "tlang_memory"
path = "src/lib.rs"

[dependencies]
tlang_ast = { path = "../../tlang_ast" }
tlang_hir = { path = "../../tlang_hir" }
inventory = { workspace = true }
log = { workspace = true }
slab = "0.4"
