[package]
name = "tlang_test_runner"
version = "0.1.0"
edition.workspace = true

[dependencies]
insta = { workspace = true, features = ["glob"] }
regex = "1.11"
serde_json = "1.0"

[lints]
workspace = true
