[package]
name = "tlang_macros"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
inventory = { workspace = true }
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
