[package]
name = "tlang_hir"
version = "0.1.0"
edition.workspace = true

[dependencies]
tlang_ast = { path = "../tlang_ast" }
serde = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
