[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.wasm-clean]
command = "rm"
args = ["-rf", "wasm"]

[tasks.clean]
dependencies = ["cargo-clean", "wasm-clean"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = [
  "--split-linked-modules",
  "--target",
  "web",
  "--out-dir",
  "wasm",
  "../../target/wasm32-unknown-unknown/release/tlang_bindings_js.wasm",
]

[tasks.wasm-opt-prepare]
linux_alias = "wasm-opt-prepare-unix"
mac_alias = "wasm-opt-prepare-unix"
windows_alias = "wasm-opt-prepare-win32"

[tasks.wasm-opt-prepare-unix]
command = "mv"
args = [
  "wasm/tlang_bindings_js_bg.wasm",
  "wasm/tlang_bindings_js_bg.unoptimized.wasm",
]

[tasks.wasm-opt-prepare-win32]
script_runner = "powershell"
script_extension = "ps1"
script = "mv -force wasm/tlang_bindings_js_bg.wasm wasm/tlang_bindings_js_bg.unoptimized.wasm"

[tasks.wasm-opt]
command = "wasm-opt"
args = [
  "-Oz", # aggressively optimize for file size
  "-g",  # but still emit names for debugging/profiling
  "-o",
  "wasm/tlang_bindings_js_bg.wasm",
  "wasm/tlang_bindings_js_bg.unoptimized.wasm",
]
dependencies = ["wasm-opt-prepare"]

[tasks.wasm-opt-cleanup]
linux_alias = "wasm-opt-cleanup-unix"
mac_alias = "wasm-opt-cleanup-unix"
windows_alias = "wasm-opt-cleanup-win32"

[tasks.wasm-opt-cleanup-unix]
command = "rm"
args = ["wasm/tlang_bindings_js_bg.unoptimized.wasm"]

[tasks.wasm-opt-cleanup-win32]
script_runner = "powershell"
script_extension = "ps1"
script = "rm wasm/tlang_bindings_js_bg.unoptimized.wasm"

[tasks.custom-default]
dependencies = ["build", "wasm-bindgen", "wasm-opt", "wasm-opt-cleanup"]

[tasks.default]
alias = "custom-default"
