[package]
name = "tlang_span"
version = "0.1.0"
edition.workspace = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }

[lints]
workspace = true
