use tlang_ast_lowering::lower_to_hir;
use tlang_codegen_js::{generator::CodegenJS, js_hir_opt::JsHirOptimizer};
use tlang_hir_opt::hir_opt::HirOptContext;
use tlang_semantics::SemanticAnalyzer;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let cmd = args.get(1).map(|s| s.as_str()).unwrap_or("");

    match cmd {
        "gen-stdlib" => gen_stdlib(),
        _ => {
            eprintln!("Usage: cargo xtask <command>");
            eprintln!();
            eprintln!("Commands:");
            eprintln!("  gen-stdlib    Compile .tlang stdlib and bundle with native JS");
            std::process::exit(1);
        }
    }
}

fn gen_stdlib() {
    let compiled_js = compile_stdlib_tlang();
    let bundle = build_bundle(&compiled_js);
    write_bundle(&bundle);
}

fn compile_stdlib_tlang() -> String {
    let source = CodegenJS::get_standard_library_source();

    let mut parser = tlang_parser::Parser::from_source(&source);
    let (mut ast, parse_meta) = parser
        .parse()
        .expect("stdlib .tlang source should parse without errors");

    let mut semantic_analyzer = SemanticAnalyzer::default();
    semantic_analyzer.add_builtin_symbols(CodegenJS::get_standard_library_symbols());
    semantic_analyzer
        .analyze(&mut ast)
        .expect("stdlib .tlang source should pass semantic analysis");

    let (mut module, meta) = lower_to_hir(
        &ast,
        &parse_meta.constant_pool_node_ids,
        semantic_analyzer.symbol_id_allocator(),
        semantic_analyzer.root_symbol_table(),
        semantic_analyzer.symbol_tables().clone(),
    );
    let mut ctx: HirOptContext = meta.into();

    let mut optimizer = JsHirOptimizer::default();
    optimizer.optimize_hir(&mut module, &mut ctx);

    let mut generator = CodegenJS::default();
    generator.generate_code(&module);
    generator.get_output().to_string()
}

/// Concatenate compiled tlang JS with the native JS files, stripping the
/// `import` lines from each native file (they are redundant in a single
/// flat bundle where all symbols are already in scope).
fn build_bundle(compiled_js: &str) -> String {
    let mut bundle = String::new();
    bundle.push_str("// Auto-generated by `cargo xtask gen-stdlib`. Do not edit directly.\n");
    bundle.push_str("// Run `cargo xtask gen-stdlib` to regenerate.\n");
    bundle.push('\n');
    bundle.push_str(compiled_js);

    for (filename, content) in CodegenJS::get_standard_library_native_js_files() {
        bundle.push('\n');
        bundle.push_str("// -- ");
        bundle.push_str(filename);
        bundle.push_str(" --\n");
        for line in content.lines() {
            if line.starts_with("import ") {
                continue;
            }
            bundle.push_str(line);
            bundle.push('\n');
        }
    }

    bundle
}

fn write_bundle(bundle: &str) {
    let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate should have a parent directory");
    let out_path = workspace_root.join("crates/tlang_codegen_js/std/dist/stdlib.js");

    std::fs::create_dir_all(out_path.parent().unwrap()).expect("failed to create dist directory");
    std::fs::write(&out_path, bundle).expect("failed to write stdlib bundle");

    println!("Written {} bytes to {}", bundle.len(), out_path.display());
}
