use clap::{Parser, Subcommand};
use oxc_allocator::Allocator;
use oxc_ast::ast::Statement;
use oxc_parser::{ParseOptions, Parser as OxcParser};
use oxc_span::{GetSpan, SourceType};
use tlang_ast_lowering::lower_to_hir;
use tlang_codegen_js::{generator::CodegenJS, js_hir_opt::JsHirOptimizer};
use tlang_hir_opt::hir_opt::HirOptContext;
use tlang_semantics::SemanticAnalyzer;

#[derive(Parser)]
#[command(name = "xtask", about = "Development task runner for tlang")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Compile .tlang stdlib and bundle with native JS
    GenStdlib,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Command::GenStdlib => gen_stdlib(),
    }
}

fn gen_stdlib() {
    let compiled_js = compile_stdlib_tlang();
    let bundle = build_bundle(&compiled_js);
    write_bundle(&bundle);
}

fn compile_stdlib_tlang() -> String {
    let source = CodegenJS::get_standard_library_source();

    let mut parser = tlang_parser::Parser::from_source(&source);
    let (mut ast, parse_meta) = parser
        .parse()
        .expect("stdlib .tlang source should parse without errors");

    let mut semantic_analyzer = SemanticAnalyzer::default();
    semantic_analyzer.add_builtin_symbols(CodegenJS::get_standard_library_symbols());
    semantic_analyzer
        .analyze(&mut ast)
        .expect("stdlib .tlang source should pass semantic analysis");

    let (mut module, meta) = lower_to_hir(
        &ast,
        &parse_meta.constant_pool_node_ids,
        semantic_analyzer.symbol_id_allocator(),
        semantic_analyzer.root_symbol_table(),
        semantic_analyzer.symbol_tables().clone(),
    );
    let mut ctx: HirOptContext = meta.into();

    let mut optimizer = JsHirOptimizer::default();
    optimizer.optimize_hir(&mut module, &mut ctx);

    let mut generator = CodegenJS::default();
    generator.generate_code(&module);
    generator.get_output().to_string()
}

/// Concatenate compiled tlang JS with the native JS files, stripping all
/// `import` declarations from each native file using the oxc parser so that
/// multi-line imports are handled correctly.
fn build_bundle(compiled_js: &str) -> String {
    let mut bundle = String::new();
    bundle.push_str("// Auto-generated by `cargo xtask gen-stdlib`. Do not edit directly.\n");
    bundle.push_str("// Run `cargo xtask gen-stdlib` to regenerate.\n");
    bundle.push('\n');
    bundle.push_str(compiled_js);

    for (filename, content) in CodegenJS::get_standard_library_native_js_files() {
        bundle.push('\n');
        bundle.push_str("// -- ");
        bundle.push_str(filename);
        bundle.push_str(" --\n");
        bundle.push_str(&strip_imports(content));
    }

    bundle
}

/// Remove all top-level `import` declarations from a JS source string.
///
/// Uses the oxc parser to locate import declarations by their byte spans so
/// that multi-line imports are handled correctly.
fn strip_imports(source: &str) -> String {
    let allocator = Allocator::default();
    let parsed = OxcParser::new(&allocator, source, SourceType::mjs())
        .with_options(ParseOptions {
            parse_regular_expression: false,
            ..Default::default()
        })
        .parse();

    // Collect import spans in reverse order so removals don't shift offsets.
    let mut import_ranges: Vec<(u32, u32)> = parsed
        .program
        .body
        .iter()
        .filter_map(|stmt| {
            if matches!(stmt, Statement::ImportDeclaration(_)) {
                let span = stmt.span();
                Some((span.start, span.end))
            } else {
                None
            }
        })
        .collect();

    import_ranges.sort_by_key(|b| std::cmp::Reverse(b.0));

    let mut result = source.to_string();
    for (start, end) in import_ranges {
        // Also consume a trailing newline if present.
        let end = if result.as_bytes().get(end as usize) == Some(&b'\n') {
            end + 1
        } else {
            end
        };
        result.replace_range(start as usize..end as usize, "");
    }

    result
}

fn write_bundle(bundle: &str) {
    let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate should have a parent directory");
    let out_path = workspace_root.join("crates/tlang_codegen_js/std/dist/stdlib.js");

    std::fs::create_dir_all(out_path.parent().unwrap()).expect("failed to create dist directory");
    std::fs::write(&out_path, bundle).expect("failed to write stdlib bundle");

    println!("Written {} bytes to {}", bundle.len(), out_path.display());
}
