[package]
name = "tlang_lexer"
version = "0.1.0"
edition.workspace = true

[dependencies]
tlang_ast = { path = "../tlang_ast" }
tlang_span = { path = "../tlang_span" }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
