[package]
name = "tlang_cli_js"
version = "0.1.0"
edition.workspace = true

[dependencies]
tlang_parser = { path = "../tlang_parser" }
tlang_codegen_js = { path = "../tlang_codegen_js" }
clap = { version = "4", features = ["derive"] }
indoc = { workspace = true }
