use std::collections::{HashMap, HashSet};

use oxc_allocator::{Allocator, Vec as OxcVec};
use oxc_ast::AstBuilder;
use oxc_ast::NONE;
use oxc_ast::ast::*;
use oxc_codegen::{Codegen, CodegenOptions, IndentChar};
use oxc_sourcemap::{SourceMap, Token};
use oxc_span::SPAN;

use crate::js_anf_transform::JsAnfTransform;
use crate::scope::Scope;
use oxc_estree::{ESTree, PrettyJSSerializer};
use tlang_defs::DefKind;
use tlang_hir as hir;
use tlang_hir_opt::hir_opt::{HirOptContext, HirPass};
use tlang_span::{HirId, HirIdAllocator, Span as TlangSpan};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct FunctionContext {
    pub name: String,
    pub parameter_bindings: Vec<String>,
    pub is_tail_recursive: bool,
}

#[derive(Debug)]
pub struct CodegenJS {
    output: String,
    js_ast_json: String,
    source_map: Option<SourceMap>,
    protocol_names: HashSet<String>,
    /// When true, suppress `export` keywords on public declarations.
    /// Used when generating a bundled multi-module output.
    bundle_mode: bool,
}

impl Default for CodegenJS {
    fn default() -> Self {
        Self::new()
    }
}

impl CodegenJS {
    pub fn new() -> Self {
        let protocol_names = Self::get_standard_library_symbols()
            .iter()
            .filter(|(_, ty)| matches!(ty, DefKind::Protocol))
            .map(|(name, _)| (*name).to_string())
            .collect();

        Self {
            output: String::new(),
            js_ast_json: String::new(),
            source_map: None,
            protocol_names,
            bundle_mode: false,
        }
    }

    /// Returns the JS identifier for a protocol name, adding a `$` prefix
    /// to avoid collision with native JS globals (e.g. `Iterator`, `Iterable`).
    pub(crate) fn protocol_js_name(name: &str) -> String {
        format!("${name}")
    }

    pub fn get_standard_library_source() -> String {
        let notice = "// This file was auto-generated by the tlang compiler.";
        let parts: &[&str] = &[
            include_str!("../std/string.tlang"),
            include_str!("../std/option.tlang"),
            include_str!("../std/result.tlang"),
            include_str!("../std/protocols.tlang"),
            include_str!("../std/math.tlang"),
            include_str!("../std/collections.tlang"),
        ];
        format!("{notice}\n{}", parts.join("\n"))
    }

    /// Returns the precompiled stdlib ES module bundle.
    ///
    /// This file is generated by `cargo xtask gen-stdlib` and committed to the
    /// repository.  It contains the compiled output of all `.tlang` stdlib
    /// files (with `export` statements) followed by the native JS
    /// implementations.
    pub fn get_precompiled_stdlib_module() -> &'static str {
        include_str!("../std/dist/stdlib.js")
    }

    /// Returns native JavaScript code appended after the compiled standard library.
    /// This provides imperative implementations for protocol methods that would
    /// stack overflow if implemented recursively in tlang.
    pub fn get_standard_library_native_js() -> String {
        Self::get_standard_library_native_js_files()
            .iter()
            .map(|(_, content)| *content)
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Returns each native JS stdlib file as `(filename, content)`, with the
    /// content embedded at compile time.  Used by `cargo xtask gen-stdlib` to
    /// build the precompiled bundle.
    pub fn get_standard_library_native_js_files() -> &'static [(&'static str, &'static str)] {
        &[
            ("globals.js", include_str!("../std/globals.js")),
            ("collections.js", include_str!("../std/collections.js")),
            ("string.js", include_str!("../std/string.js")),
            ("regex.js", include_str!("../std/regex.js")),
            ("string_buf.js", include_str!("../std/string_buf.js")),
        ]
    }

    pub fn get_standard_library_symbols() -> &'static [(&'static str, DefKind)] {
        &[
            ("Option", DefKind::Enum),
            ("Result", DefKind::Enum),
            ("Option::Some", DefKind::EnumVariant(1)),
            ("Option::None", DefKind::EnumVariant(0)),
            ("Result::Ok", DefKind::EnumVariant(1)),
            ("Result::Err", DefKind::EnumVariant(1)),
            ("Some", DefKind::EnumVariant(1)),
            ("None", DefKind::EnumVariant(0)),
            ("Ok", DefKind::EnumVariant(1)),
            ("Err", DefKind::EnumVariant(1)),
            ("Functor", DefKind::Protocol),
            ("Functor::map", DefKind::ProtocolMethod(2)),
            ("Match", DefKind::Protocol),
            ("Match::matches", DefKind::ProtocolMethod(2)),
            ("Regex", DefKind::Struct),
            ("Iterable", DefKind::Protocol),
            ("Iterable::iter", DefKind::ProtocolMethod(1)),
            ("Iterator", DefKind::Protocol),
            ("Iterator::next", DefKind::ProtocolMethod(1)),
            ("Display", DefKind::Protocol),
            ("Display::to_string", DefKind::ProtocolMethod(1)),
            ("len", DefKind::Function(1)),
            ("log", DefKind::Function(u16::MAX)),
            ("math", DefKind::Module),
            ("math::pi", DefKind::Variable),
            ("math::max", DefKind::Function(u16::MAX)),
            ("math::min", DefKind::Function(u16::MAX)),
            ("math::floor", DefKind::Function(1)),
            ("math::random", DefKind::Function(0)),
            ("random_int", DefKind::Function(1)),
            ("math::sqrt", DefKind::Function(1)),
            ("compose", DefKind::Function(2)),
            ("re", DefKind::Function(2)),
            ("map", DefKind::Function(2)),
            ("panic", DefKind::Function(1)),
            ("string", DefKind::Module),
            ("string::from_char_code", DefKind::Function(1)),
            ("string::char_code_at", DefKind::Function(2)),
            ("string::StringBuf", DefKind::Struct),
        ]
    }

    pub fn generate_code(&mut self, module: &hir::Module) {
        self.run_codegen(module, None, None);
    }

    /// Enable bundle mode: suppresses `export` keywords on public declarations.
    pub fn set_bundle_mode(&mut self, bundle: bool) {
        self.bundle_mode = bundle;
    }

    /// Register a user-defined protocol name so the codegen emits `$ProtocolName`
    /// instead of `ProtocolName` when generating path expressions.
    pub fn register_protocol(&mut self, name: &str) {
        self.protocol_names.insert(name.to_string());
    }

    /// Generate code and produce a source map mapping generated JS back to the
    /// original tlang source. `source_name` is stored as the source file name in
    /// the map; `source_text` is the original tlang source used to build it.
    pub fn generate_code_with_source_map(
        &mut self,
        module: &hir::Module,
        source_name: &str,
        source_text: &str,
    ) {
        self.run_codegen(module, Some(source_text), Some(source_name));
    }

    fn run_codegen(
        &mut self,
        module: &hir::Module,
        source_text: Option<&str>,
        source_name: Option<&str>,
    ) {
        // ANF is required: the OXC-based codegen assumes all expressions in
        // value positions are JS-expressible. Clone + ANF to guarantee this.
        let mut module = module.clone();
        let mut anf = JsAnfTransform::default();
        let mut ctx = HirOptContext {
            symbols: HashMap::new(),
            hir_id_allocator: HirIdAllocator::default(),
            current_scope: HirId::new(1),
        };
        anf.optimize_hir(&mut module, &mut ctx);

        let allocator = Allocator::default();
        let ast = AstBuilder::new(&allocator);
        let mut inner = InnerCodegen::new(ast, self.protocol_names.clone());
        inner.bundle_mode = self.bundle_mode;
        if let Some(st) = source_text {
            inner = inner.with_source_text(st.to_string());
        }
        let program = inner.generate_module(&module);

        let mut serializer = PrettyJSSerializer::new(false);
        program.serialize(&mut serializer);
        self.js_ast_json = serializer.into_string();

        let mut options = CodegenOptions {
            indent_char: IndentChar::Space,
            indent_width: 4,
            ..CodegenOptions::default()
        };
        if let Some(name) = source_name {
            options.source_map_path = Some(std::path::PathBuf::from(name));
        }

        let result = Codegen::new().with_options(options).build(&program);
        self.output = result.code;
        self.source_map = result.map;
    }

    pub fn get_output(&self) -> &str {
        &self.output
    }

    pub fn get_js_ast_json(&self) -> &str {
        &self.js_ast_json
    }

    pub fn get_source_map(&self) -> Option<&SourceMap> {
        self.source_map.as_ref()
    }

    /// Returns the source map serialized as a JSON string, or `None` if no
    /// source map was generated. The generated line positions in the map
    /// correspond to `get_output()` — call [`shift_source_map_lines`] if you
    /// need to account for lines prepended to the final file (e.g. stdlib).
    pub fn get_source_map_json(&self) -> Option<String> {
        self.source_map.as_ref().map(|m| m.to_json_string())
    }
}

/// Shift every generated mapping in `map_json` down by `line_offset` lines.
///
/// This is used when the compiled output is prefixed with a preamble such as
/// the stdlib, so generated JS line numbers still point back to the original
/// tlang source locations.
///
/// # Panics
///
/// Panics if `map_json` is not a valid source map JSON string.
pub fn shift_source_map_lines(map_json: &str, line_offset: usize) -> String {
    if line_offset == 0 {
        return map_json.to_string();
    }

    let source_map =
        SourceMap::from_json_string(map_json).expect("generated source map should be valid JSON");
    let mut shifted = SourceMap::new(
        source_map.get_file().cloned(),
        source_map.get_names().cloned().collect(),
        source_map.get_source_root().map(str::to_owned),
        source_map.get_sources().cloned().collect(),
        source_map
            .get_source_contents()
            .map(|content| content.cloned())
            .collect(),
        source_map
            .get_tokens()
            .map(|token| {
                Token::new(
                    token.get_dst_line() + line_offset as u32,
                    token.get_dst_col(),
                    token.get_src_line(),
                    token.get_src_col(),
                    token.get_source_id(),
                    token.get_name_id(),
                )
            })
            .collect::<Vec<_>>()
            .into_boxed_slice(),
        None,
    );

    if let Some(ignore_list) = source_map.get_x_google_ignore_list() {
        shifted.set_x_google_ignore_list(ignore_list.to_vec());
    }

    if let Some(debug_id) = source_map.get_debug_id() {
        shifted.set_debug_id(debug_id);
    }

    shifted.to_json_string()
}

// ---------------------------------------------------------------------------
// InnerCodegen: arena-scoped codegen that builds an OXC AST
// ---------------------------------------------------------------------------

pub(crate) struct InnerCodegen<'a> {
    pub ast: AstBuilder<'a>,
    pub scopes: Scope,
    pub function_context_stack: Vec<FunctionContext>,
    pub protocol_names: HashSet<String>,
    /// When true, suppress `export` keywords on public declarations.
    pub bundle_mode: bool,
    /// Original tlang source text. When non-empty, it's prepended to
    /// `comment_source` as the combined `Program.source_text`, enabling OXC's
    /// built-in source map generation (which reads byte offsets from node spans).
    source_text: String,
    /// Buffer of synthetic source text containing comment strings.
    /// OXC codegen reads comment content from Program.source_text using byte spans.
    comment_source: String,
    /// Collected OXC comments to be attached to the Program.
    oxc_comments: Vec<oxc_ast::Comment>,
    /// Counter for assigning unique span start positions to comment-bearing
    /// statement nodes, ensuring comment attachment keys are always distinct
    /// (even when multiple HIR nodes derive from the same source position).
    span_counter: u32,
}

impl<'a> InnerCodegen<'a> {
    pub fn new(ast: AstBuilder<'a>, protocol_names: HashSet<String>) -> Self {
        Self {
            ast,
            scopes: Scope::default(),
            function_context_stack: Vec::new(),
            protocol_names,
            bundle_mode: false,
            source_text: String::new(),
            comment_source: String::new(),
            oxc_comments: Vec::new(),
            span_counter: 1,
        }
    }

    pub fn with_source_text(mut self, source_text: String) -> Self {
        self.source_text = source_text;
        self
    }

    pub fn generate_module(&mut self, module: &hir::Module) -> Program<'a> {
        let stmts = self.generate_stmts(&module.block.stmts);
        let body = self.ast.vec_from_iter(stmts);
        // Combine the original tlang source (for source map byte-offset lookups)
        // with the synthetic comment buffer (for OXC's comment printer).
        let combined = format!("{}{}", self.source_text, self.comment_source);
        let source_text = self.ast.allocator.alloc_str(&combined);
        let comments = self.ast.vec_from_iter(self.oxc_comments.drain(..));
        self.ast.program(
            SPAN,
            SourceType::mjs(),
            source_text,
            comments,
            None,
            self.ast.vec(),
            body,
        )
    }

    /// Convert a tlang span to an OXC span using byte offsets.
    pub fn hir_span(span: TlangSpan) -> oxc_span::Span {
        oxc_span::Span::new(span.start, span.end)
    }

    // -- Scope helpers -------------------------------------------------------

    pub fn push_scope(&mut self) {
        self.scopes = Scope::new(Some(Box::new(self.scopes.clone())));
    }

    pub fn pop_scope(&mut self) {
        if let Some(parent) = self.scopes.get_parent() {
            self.scopes = parent.clone();
        }
    }

    pub fn current_scope(&mut self) -> &mut Scope {
        &mut self.scopes
    }

    // -- Function context helpers --------------------------------------------

    pub fn get_function_context(&self) -> Option<&FunctionContext> {
        self.function_context_stack.last()
    }

    pub fn push_function_context(
        &mut self,
        name: &str,
        parameters: &[hir::FunctionParameter],
        parameter_bindings: &[String],
        is_tail_recursive: bool,
    ) {
        let parameter_bindings = if !is_tail_recursive {
            vec![]
        } else if parameters.len() == parameter_bindings.len() {
            parameter_bindings.to_vec()
        } else {
            parameters
                .iter()
                .map(|param| {
                    if param.name.is_wildcard() {
                        self.scopes.declare_tmp_variable()
                    } else {
                        param.name.to_string()
                    }
                })
                .collect()
        };

        self.function_context_stack.push(FunctionContext {
            name: name.to_string(),
            parameter_bindings,
            is_tail_recursive,
        });
    }

    pub fn pop_function_context(&mut self) {
        self.function_context_stack.pop();
    }

    // -- Protocol helpers ----------------------------------------------------

    pub fn is_protocol(&self, name: &str) -> bool {
        self.protocol_names.contains(name)
    }

    pub fn register_protocol(&mut self, name: &str) {
        self.protocol_names.insert(name.to_string());
    }

    // -- Comment helpers -------------------------------------------------------

    /// Allocate a unique span start for a statement node.
    /// OXC's codegen uses `span.start` to look up attached comments.
    fn next_node_start(&mut self) -> u32 {
        let id = self.span_counter;
        self.span_counter += 1;
        id
    }

    /// Attach HIR leading comments to an OXC statement. A unique counter-based
    /// ID is used as the attachment key so that nodes derived from the same
    /// source position (e.g., a function clause and its pattern-dispatch branch)
    /// don't accidentally share a `span.start` and trigger duplicate comments.
    /// Comment text is appended to `comment_source`, placed after the original
    /// source in the combined `Program.source_text`.
    pub fn attach_leading_comments(
        &mut self,
        stmt: &mut Statement<'a>,
        comments: &[tlang_ast::token::CommentToken],
    ) {
        use oxc_ast::{Comment, CommentKind, CommentPosition};
        use oxc_span::GetSpanMut;

        if comments.is_empty() {
            return;
        }

        let node_start = self.next_node_start();
        let span = stmt.span_mut();
        span.start = node_start;
        if span.end < node_start {
            span.end = node_start;
        }

        for comment_token in comments {
            let (text, oxc_kind) = match comment_token.kind {
                tlang_ast::token::CommentKind::SingleLine => {
                    (format!("//{}", comment_token.text), CommentKind::Line)
                }
                tlang_ast::token::CommentKind::MultiLine => (
                    format!("/*{}*/", comment_token.text),
                    CommentKind::MultiLineBlock,
                ),
            };

            // Offset the comment span past the original source text so that the
            // combined Program.source_text (original + comment_source) is indexed
            // correctly by both the source map builder and the comment printer.
            let start = self.source_text.len() as u32 + self.comment_source.len() as u32;
            self.comment_source.push_str(&text);
            self.comment_source.push('\n');
            let end = start + text.len() as u32;

            self.oxc_comments.push(Comment {
                span: oxc_span::Span::new(start, end),
                attached_to: node_start,
                kind: oxc_kind,
                position: CommentPosition::Leading,
                newlines: CommentNewlines::Leading | CommentNewlines::Trailing,
                content: oxc_ast::CommentContent::None,
            });
        }
    }

    // -- AST building helpers ------------------------------------------------

    /// Allocate a string into the arena, returning a reference with lifetime `'a`.
    pub fn alloc_str(&self, s: &str) -> &'a str {
        self.ast.allocator.alloc_str(s)
    }

    pub fn ident_expr(&self, name: &str) -> Expression<'a> {
        self.ast.expression_identifier(SPAN, self.alloc_str(name))
    }

    pub fn ident_name(&self, name: &str) -> IdentifierName<'a> {
        self.ast.identifier_name(SPAN, self.alloc_str(name))
    }

    pub fn binding_ident(&self, name: &str) -> BindingIdentifier<'a> {
        self.ast.binding_identifier(SPAN, self.alloc_str(name))
    }

    pub fn num_expr(&self, value: f64) -> Expression<'a> {
        self.ast
            .expression_numeric_literal(SPAN, value, None, NumberBase::Decimal)
    }

    pub fn str_expr(&self, value: &str) -> Expression<'a> {
        self.ast
            .expression_string_literal(SPAN, self.alloc_str(value), None)
    }

    pub fn bool_expr(&self, value: bool) -> Expression<'a> {
        self.ast.expression_boolean_literal(SPAN, value)
    }

    pub fn undefined_expr(&self) -> Expression<'a> {
        self.ident_expr("undefined")
    }

    pub fn this_expr(&self) -> Expression<'a> {
        self.ast.expression_this(SPAN)
    }

    pub fn static_member_expr(&self, object: Expression<'a>, property: &str) -> Expression<'a> {
        Expression::StaticMemberExpression(self.ast.alloc_static_member_expression(
            SPAN,
            object,
            self.ident_name(property),
            false,
        ))
    }

    /// Build `object?.property` (optional chaining member access).
    pub fn optional_static_member_expr(
        &self,
        object: Expression<'a>,
        property: &str,
    ) -> Expression<'a> {
        Expression::StaticMemberExpression(self.ast.alloc_static_member_expression(
            SPAN,
            object,
            self.ident_name(property),
            true,
        ))
    }

    /// Wrap an expression in `ChainExpression` for optional chaining.
    pub fn chain_expr(&self, inner: Expression<'a>) -> Expression<'a> {
        let chain_element = inner
            .into_chain_element()
            .expect("expected chainable expression");
        self.ast.expression_chain(SPAN, chain_element)
    }

    pub fn computed_member_expr(
        &self,
        object: Expression<'a>,
        index: Expression<'a>,
    ) -> Expression<'a> {
        Expression::ComputedMemberExpression(
            self.ast
                .alloc_computed_member_expression(SPAN, object, index, false),
        )
    }

    pub fn assignment_target_ident(&self, name: &str) -> AssignmentTarget<'a> {
        AssignmentTarget::from(
            self.ast
                .simple_assignment_target_assignment_target_identifier(SPAN, self.alloc_str(name)),
        )
    }

    pub fn assignment_target_member(
        &self,
        object: Expression<'a>,
        property: &str,
    ) -> AssignmentTarget<'a> {
        AssignmentTarget::from(SimpleAssignmentTarget::StaticMemberExpression(
            self.ast
                .alloc_static_member_expression(SPAN, object, self.ident_name(property), false),
        ))
    }

    pub fn assignment_target_computed(
        &self,
        object: Expression<'a>,
        index: Expression<'a>,
    ) -> AssignmentTarget<'a> {
        AssignmentTarget::from(SimpleAssignmentTarget::ComputedMemberExpression(
            self.ast
                .alloc_computed_member_expression(SPAN, object, index, false),
        ))
    }

    pub fn assign_expr(
        &self,
        target: AssignmentTarget<'a>,
        value: Expression<'a>,
    ) -> Expression<'a> {
        self.ast
            .expression_assignment(SPAN, AssignmentOperator::Assign, target, value)
    }

    pub fn binding_pattern_ident(&self, name: &str) -> BindingPattern<'a> {
        self.ast
            .binding_pattern_binding_identifier(SPAN, self.alloc_str(name))
    }

    pub fn formal_param(&self, name: &str) -> FormalParameter<'a> {
        self.ast.formal_parameter(
            SPAN,
            self.ast.vec(),
            self.binding_pattern_ident(name),
            NONE,
            NONE,
            false,
            None,
            false,
            false,
        )
    }

    pub fn formal_params(&self, items: OxcVec<'a, FormalParameter<'a>>) -> FormalParameters<'a> {
        self.ast
            .formal_parameters(SPAN, FormalParameterKind::FormalParameter, items, NONE)
    }

    pub fn fn_body(&self, stmts: OxcVec<'a, Statement<'a>>) -> FunctionBody<'a> {
        self.ast.function_body(SPAN, self.ast.vec(), stmts)
    }

    /// Create a `let` variable declaration statement with optional initializer.
    pub fn let_decl(&self, name: &str, init: Option<Expression<'a>>) -> Statement<'a> {
        let declarator = self.ast.variable_declarator(
            SPAN,
            VariableDeclarationKind::Let,
            self.binding_pattern_ident(name),
            NONE,
            init,
            false,
        );
        Statement::VariableDeclaration(self.ast.alloc_variable_declaration(
            SPAN,
            VariableDeclarationKind::Let,
            self.ast.vec1(declarator),
            false,
        ))
    }

    /// Create a `const` variable declaration statement.
    pub fn const_decl(&self, name: &str, init: Expression<'a>) -> Statement<'a> {
        let declarator = self.ast.variable_declarator(
            SPAN,
            VariableDeclarationKind::Const,
            self.binding_pattern_ident(name),
            NONE,
            Some(init),
            false,
        );
        Statement::VariableDeclaration(self.ast.alloc_variable_declaration(
            SPAN,
            VariableDeclarationKind::Const,
            self.ast.vec1(declarator),
            false,
        ))
    }

    /// Create a let destructuring declaration: `let [a, b, ...rest] = expr;`
    pub fn let_array_destructuring(
        &self,
        elements: OxcVec<'a, Option<BindingPattern<'a>>>,
        rest: Option<BindingPattern<'a>>,
        init: Expression<'a>,
    ) -> Statement<'a> {
        let rest_element = rest.map(|r| self.ast.alloc_binding_rest_element(SPAN, r));
        let pattern = self
            .ast
            .binding_pattern_array_pattern(SPAN, elements, rest_element);
        let declarator = self.ast.variable_declarator(
            SPAN,
            VariableDeclarationKind::Let,
            pattern,
            NONE,
            Some(init),
            false,
        );
        Statement::VariableDeclaration(self.ast.alloc_variable_declaration(
            SPAN,
            VariableDeclarationKind::Let,
            self.ast.vec1(declarator),
            false,
        ))
    }

    pub fn expr_stmt(&self, expr: Expression<'a>) -> Statement<'a> {
        self.ast.statement_expression(SPAN, expr)
    }

    pub fn block_stmt(&self, stmts: Vec<Statement<'a>>) -> Statement<'a> {
        self.ast
            .statement_block(SPAN, self.ast.vec_from_iter(stmts))
    }

    pub fn call_expr(&self, callee: Expression<'a>, args: Vec<Argument<'a>>) -> Expression<'a> {
        self.ast
            .expression_call(SPAN, callee, NONE, self.ast.vec_from_iter(args), false)
    }
}

#[cfg(test)]
mod tests {
    use super::shift_source_map_lines;
    use oxc_sourcemap::{SourceMap, Token};

    #[test]
    fn shift_source_map_lines_preserves_metadata_and_offsets_tokens() {
        let mut source_map = SourceMap::new(
            Some("out.js".into()),
            vec!["main".into()],
            Some("src".to_string()),
            vec!["input.tlang".into()],
            vec![Some("fn main() { 1 }".into())],
            vec![
                Token::new(0, 0, 0, 0, Some(0), Some(0)),
                Token::new(2, 4, 0, 3, Some(0), None),
            ]
            .into_boxed_slice(),
            None,
        );
        source_map.set_debug_id("debug-id");
        source_map.set_x_google_ignore_list(vec![0]);

        let shifted_json = shift_source_map_lines(&source_map.to_json_string(), 3);
        let shifted = SourceMap::from_json_string(&shifted_json).unwrap();
        let shifted_lines = shifted
            .get_tokens()
            .map(|token| token.get_dst_line())
            .collect::<Vec<_>>();

        assert_eq!(shifted_lines, vec![3, 5]);
        assert_eq!(shifted.get_file().map(|file| file.as_ref()), Some("out.js"));
        assert_eq!(shifted.get_source_root(), Some("src"));
        assert_eq!(shifted.get_debug_id(), Some("debug-id"));
        assert_eq!(shifted.get_x_google_ignore_list(), Some(&[0][..]));
    }
}
