name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup-rust:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cargo
        with:
          save-cache: 'true'

      - name: Show Rust version
        run: |
          rustup show
          rustc -Vv
          cargo -V

  lint-js:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24.0.2"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: lit-analyzer
        run: npx lit-analyzer src
        working-directory: ./tlang-playground

      - name: TypeCheck
        run: npm run typecheck

  lint-rust:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [setup-rust]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cargo

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --all-features -- -D warnings

  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [setup-rust]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cargo

      - uses: actions/setup-node@v6
        with:
          node-version: "24.0.2"

      - name: Test Runner
        run: make test

      - name: Test JS bindings
        run: make test-bindings-js

  coverage:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [setup-rust]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cargo

      - name: Run coverage
        run: make test-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          # Default output directory used by `cargo llvm-cov report --html`
          path: target/llvm-cov/html/

  build-playground:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [lint-js, lint-rust, test, coverage]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-cargo

      - name: Install binaryen
        run: |
          wget -q https://github.com/WebAssembly/binaryen/releases/download/version_119/binaryen-version_119-x86_64-linux.tar.gz
          tar xzf binaryen-version_119-x86_64-linux.tar.gz
          echo "$(pwd)/binaryen-version_119/bin" >> "$GITHUB_PATH"

      - uses: actions/setup-node@v6
        with:
          node-version: "24.0.2"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build playground
        run: npm run build -- -- --base=/tlang

      - name: Upload artifact
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/upload-pages-artifact@v4
        with:
          path: tlang-playground/dist/

  test-tree-sitter:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24.0.2"

      - name: Install tree-sitter-tlang dependencies
        run: npm ci

      - name: Test tree-sitter corpus
        run: npm test
        working-directory: ./tree-sitter-tlang

  deploy-pages:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    needs: ["build-playground"]

    permissions:
      actions: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
