name: Publish Playground to Github Pages

on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add cache for cargo
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            # Taken from <https://doc.rust-lang.org/nightly/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci>.
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            # contains package information of crates installed via `cargo install`.
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-0
          restore-keys: ${{ runner.os }}-cargo-0

      - name: Install rustup-toolchain-install-master
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          cargo install -f rustup-toolchain-install-master
          cargo install -f wasm-bindgen-cli
          cargo install -f cargo-make

      - name: Install binaryen
        run: sudo apt install -y binaryen

      - name: Install wasm toolchain
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Show Rust version
        run: |
          rustup show
          rustc -Vv
          cargo -V
          cargo make -V

      - name: Cargo Make
        run: cargo make

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install playground dependencies
        run: npm ci

      - name: Build playground
        working-directory: tlang-playground
        run: npm run build -- --base=/tlang

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tlang-playground/dist

  deploy-pages:
    runs-on: ubuntu-latest
    needs: ["build"]

    permissions:
      actions: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
