[package]
name = "tlang_ast"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
pretty_assertions = { workspace = true }
